name: "Pull Request Labeler"

permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request_target:

jobs:
  triage:
    permissions:
      contents: read # may be required due to overwrite/add ambiguity
      pull-requests: write # required to apply labels to PRs
    runs-on: ubuntu-latest
    steps:
      - name: Check for conflicting PRs
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "_üö®_ Conflicts! _üö®_"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "Pull Request —Å–æ–¥–µ—Ä–∂–∏—Ç –∫–æ–Ω—Ñ–ª–∏–∫—Ç—ã. –£—Å—Ç—Ä–∞–Ω–∏—Ç–µ –∏—Ö, —á—Ç–æ–±—ã –º—ã —Å–º–æ–≥–ª–∏ –æ—Ü–µ–Ω–∏—Ç—å –∏ –ø—Ä–∏–Ω—è—Ç—å –∑–∞–ø—Ä–æ—Å."
      - name: Apply labels based on changed files
        if: github.event_name != 'push'
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true
          configuration-path: .github/labeler.yml
